- name: copy file to server
  uses: appleboy/scp-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.SSH_USER_NAME }}
    password: ${{ secrets.SSH_PWD }}
    source: "."
    target: "/var/www/html"
